import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tax Intelligence — AI-Powered Indian Tax Filing",
  description:
    "Upload Form 16, Form 26AS, and salary slips. Our AI engine extracts, analyses, and advises on the best tax regime for you.",
};

const FEATURES = [
  {
    icon: "📄",
    title: "Smart Document Parsing",
    desc: "Upload Form 16, Form 26AS, AIS, salary slips, and investment proofs. Our AI extracts every number and field automatically.",
  },
  {
    icon: "🤖",
    title: "AI-Driven Tax Insights",
    desc: "Compare old vs new regime, see effective tax rates, and get actionable deduction recommendations — all generated by GPT-4.",
  },
  {
    icon: "💬",
    title: "Conversational Tax Advisor",
    desc: "Ask anything about your financial profile in plain English. Get personalised answers grounded in your actual documents.",
  },
  {
    icon: "🔒",
    title: "Bank-Grade Security",
    desc: "Documents stored in isolated Cloudflare R2 buckets. JWT auth, httpOnly cookies, rate limiting, and full audit logs.",
  },
];

const SUPPORTED_DOCS = [
  "Form 16 / 16A",
  "Form 26AS",
  "AIS & TIS",
  "Salary Slips",
  "Bank Statements",
  "Investment Proofs",
  "Home Loan Statements",
  "Rent Receipts",
];

export default function TaxLandingPage() {
  return (
    <div className="relative">
      {/* Hero */}
      <section className="relative py-24 px-6 text-center overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-primary/5 to-transparent pointer-events-none" />
        <div className="relative max-w-3xl mx-auto space-y-6">
          <span className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-4 py-1.5 text-xs font-semibold tracking-wide text-primary uppercase">
            AI Tax Intelligence — FY 2024-25
          </span>
          <h1 className="text-4xl sm:text-6xl font-extrabold leading-tight tracking-tight font-heading">
            Stop guessing your taxes.
            <br />
            <span className="text-primary">Let AI do it.</span>
          </h1>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            Upload your Indian tax documents. Our AI engine parses them,
            builds your financial profile, compares tax regimes, and gives
            you actionable advice — all in minutes.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-2">
            <Link
              href="/tax/register"
              className="inline-flex items-center justify-center rounded-[2px] bg-primary px-8 py-3 text-sm font-semibold text-primary-foreground transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
            >
              Get started free
            </Link>
            <Link
              href="/tax/login"
              className="inline-flex items-center justify-center rounded-[2px] border border-border px-8 py-3 text-sm font-semibold text-foreground transition-colors hover:bg-accent"
            >
              Sign in
            </Link>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-20 px-6">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-2xl font-bold font-heading text-center mb-12">
            Everything you need for smarter tax filing
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {FEATURES.map((f) => (
              <div
                key={f.title}
                className="rounded-[2px] border border-border bg-card p-6 space-y-3"
              >
                <div className="text-3xl">{f.icon}</div>
                <h3 className="font-semibold font-heading">{f.title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  {f.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Supported documents */}
      <section className="py-16 px-6 border-t border-border">
        <div className="max-w-4xl mx-auto text-center space-y-8">
          <h2 className="text-2xl font-bold font-heading">
            Supported document types
          </h2>
          <div className="flex flex-wrap justify-center gap-3">
            {SUPPORTED_DOCS.map((d) => (
              <span
                key={d}
                className="rounded-full border border-border bg-muted px-4 py-1.5 text-xs font-medium text-muted-foreground"
              >
                {d}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-6">
        <div className="max-w-2xl mx-auto text-center space-y-6 rounded-[2px] border border-primary/20 bg-primary/5 p-10">
          <h2 className="text-3xl font-bold font-heading">
            Ready to simplify your taxes?
          </h2>
          <p className="text-muted-foreground">
            Join and let AI handle the complexity while you focus on saving
            more.
          </p>
          <Link
            href="/tax/register"
            className="inline-flex items-center justify-center rounded-[2px] bg-primary px-10 py-3 text-sm font-semibold text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Create free account
          </Link>
        </div>
      </section>
    </div>
  );
}
